# -*- coding: utf-8 -*-
"""Moco_test_training

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z78yMf6okdHLmd7Am_6Tq0KWBJQAg5Ql
"""


import gc
import os
from pathlib import Path
import torch
from torch import Tensor
from torch.utils.data import DataLoader
from torchgeo.datasets import NonGeoDataset
import numpy as np
import rasterio
from typing import Any, Callable, Dict, List, Optional, Sequence, Union
from matplotlib.pyplot import Figure
from collections.abc import Callable
from lightning.pytorch import LightningDataModule
import time
from torchvision.transforms import v2
from lightning.pytorch import Trainer
from lightning.pytorch.callbacks import ModelCheckpoint
from lightning.pytorch.loggers import TensorBoardLogger
from torchgeo.trainers import MoCoTask
import torch.nn.functional as F
from lightly.utils.scheduler import cosine_schedule
import torch.nn as nn
import kornia.augmentation as K
import torchgeo.transforms as T
print('cwd',os.getcwd())
print(torch.cuda.is_available())

def moco_augmentations(
    version: int, size: int, weights: Tensor
) -> tuple[nn.Module, nn.Module]:
    """Data augmentations used by MoCo.

    Args:
        version: Version of MoCo.
        size: Size of patch to crop.
        weights: Weight vector for grayscale computation.

    Returns:
        Data augmentation pipelines.
    """
    # https://github.com/facebookresearch/moco/blob/main/main_moco.py#L326
    # https://github.com/facebookresearch/moco-v3/blob/main/main_moco.py#L261
    ks = size // 10 // 2 * 2 + 1
    if version == 1:
        # Same as InstDict: https://arxiv.org/abs/1805.01978
        aug1 = aug2 = K.AugmentationSequential(
            K.RandomResizedCrop(size=(size, size), scale=(0.2, 1)),
            T.RandomGrayscale(weights=weights, p=0.2),
            # Not appropriate for multispectral imagery, seasonal contrast used instead
            # K.ColorJitter(brightness=0.4, contrast=0.4, saturation=0.4, hue=0.4, p=1)
            K.RandomBrightness(brightness=(0.6, 1.4), p=1.0),
            K.RandomContrast(contrast=(0.6, 1.4), p=1.0),
            K.RandomHorizontalFlip(),
            K.RandomVerticalFlip(),  # added
            data_keys=['input'],
        )
    elif version == 2:
        # Similar to SimCLR: https://arxiv.org/abs/2002.05709
        aug1 = aug2 = K.AugmentationSequential(
            K.RandomResizedCrop(size=(size, size), scale=(0.2, 1)),
            # Not appropriate for multispectral imagery, seasonal contrast used instead
            # K.ColorJitter(
            #     brightness=0.4, contrast=0.4, saturation=0.4, hue=0.1, p=0.8
            # )
            K.RandomBrightness(brightness=(0.6, 1.4), p=0.8),
            K.RandomContrast(contrast=(0.6, 1.4), p=0.8),
            T.RandomGrayscale(weights=weights, p=0.2),
            K.RandomGaussianBlur(kernel_size=(ks, ks), sigma=(0.1, 2), p=0.5),
            K.RandomHorizontalFlip(),
            K.RandomVerticalFlip(),  # added
            K.Normalize(mean=[0.153467, 0.141859, 0.309777, 0.363888], std=[0.104461, 0.131514, 0.147038, 0.174622]), 
            data_keys=['input'],
        )
    else:
        # Same as BYOL: https://arxiv.org/abs/2006.07733
        aug1 = K.AugmentationSequential(
            K.RandomResizedCrop(size=(size, size), scale=(0.08, 1)),
            # Not appropriate for multispectral imagery, seasonal contrast used instead
            # K.ColorJitter(
            #     brightness=0.4, contrast=0.4, saturation=0.2, hue=0.1, p=0.8
            # )
            K.RandomBrightness(brightness=(0.85, 1.15), p=0.3),
            K.RandomContrast(contrast=(0.85, 1.15), p=0.3),
            #T.RandomGrayscale(weights=weights, p=0.2),
            K.RandomGaussianBlur(kernel_size=(ks, ks), sigma=(0.1, 0.8), p=0.15),
            K.RandomHorizontalFlip(),
            K.RandomVerticalFlip(),
            K.Normalize(mean=[0.153467, 0.141859, 0.309777, 0.363888], std=[0.104461, 0.131514, 0.147038, 0.174622]),  # added
            data_keys=['input'],
        )
        aug2 = K.AugmentationSequential(
            K.RandomResizedCrop(size=(size, size), scale=(0.08, 1)),
            # Not appropriate for multispectral imagery, seasonal contrast used instead
            # K.ColorJitter(
            #     brightness=0.4, contrast=0.4, saturation=0.2, hue=0.1, p=0.8
            # )
            K.RandomBrightness(brightness=(0.85, 1.15), p=0.3),
            K.RandomContrast(contrast=(0.85, 1.15), p=0.3),
            #T.RandomGrayscale(weights=weights, p=0.2),
            #K.RandomGaussianBlur(kernel_size=(ks, ks), sigma=(0.1, 2), p=0.1),
            #.RandomSolarize(p=0.2),
            K.RandomHorizontalFlip(),
            K.RandomVerticalFlip(),  # added
            K.Normalize(mean=[0.153467, 0.141859, 0.309777, 0.363888], std=[0.104461, 0.131514, 0.147038, 0.174622]), 
            data_keys=['input'],
        )
    return aug1, aug2

aug1, aug2 = moco_augmentations(version=3, size=224, weights=Tensor([0.25, 0.25, 0.25, 0.25]))

class MultiSpectralChipDataset(NonGeoDataset):
    """MultiSpectralChipDataset.

    A dataset for multi-spectral image chips compatible with TorchGeo's MoCoTask.

    Dataset features:
    * 7-channel multi-spectral images
    * Pre-chipped 256x256 images
    * No geospatial information (pre-processed chips)

    Dataset format:
    * Input: 7-channel TIFF files with shape (C, H, W)
    * Channels: B, G, R, RE, NIR, NDVI, NDVIre
    * File naming: *_chip_*.tif

    .. versionadded: 0.5
    """

    def __init__(
        self,
        root: Path = 'data',
        split: str = 'train',
        transforms: Callable[[dict[str, Tensor]], dict[str, Tensor]] | None = None,
        download: bool = False,
        batch_size: int = 84,
        shuffle: bool = True,
        num_workers: int = 4,
        pin_memory: bool = False,
    ) -> None:
        """Initialize the dataset.

        Args:
            root: Root directory where the data is located
            split: One of "train", "val", or "test" (default: "train")
            transforms: A function/transform that takes input sample and returns a transformed version
            download: If True, download dataset and store it in the root directory
            batch_size: Batch size for the DataLoader
            shuffle: Whether to shuffle the data
            num_workers: Number of worker processes for data loading
            pin_memory: Whether to pin memory for faster GPU transfer
        """
        super().__init__()  # NonGeoDataset doesn't accept transforms in __init__
        self.root = Path(root)
        self.split = split
        self.transforms = transforms
        self.chips = []

        # Find all chip files
        for chip_file in self.root.glob("*.tif"):
            self.chips.append(chip_file)

        if not self.chips:
            raise RuntimeError(f"No chip files found in {root}")

        print(f"Found {len(self.chips)} chips")

        # Verify the first chip has 4 or 5 channels
        with rasterio.open(self.chips[0]) as src:
            n_channels = src.count
            print(f"Number of channels in first chip: {n_channels}")
            #if n_channels not in [5, 6]:
            #    raise RuntimeError(f"Expected 4 or 5 channels, but found {n_channels}")

        # Create DataLoader
        self.dataloader = DataLoader(
            self,
            batch_size=batch_size,
            shuffle=shuffle,
            num_workers=num_workers,
            pin_memory=pin_memory
            #persistent_workers = False
        )

    def __getitem__(self, index: int) -> dict[str, Tensor]:
        """Get a single sample from the dataset.

        Args:
            index: Index of the item to get

        Returns:
            Dictionary containing the image data as a tensor
        """
        chip_path = self.chips[index]

        # Read the multi-spectral image
        with rasterio.open(chip_path) as src:
            image = src.read()  # Shape: (C, H, W)

        # Always load 4 channels: if 5 channels exist, skip the first channel
        #if image.shape[0] == 6:
        #    image = image[1:, :, :]  # Skip first channel, take channels 1-4
        #elif image.shape[0] == 5:
        #    image = image  # Use all 4 channels as-is
        #else:
        #    raise RuntimeError(f"Unexpected number of channels: {image.shape[0]}")

        # Convert to float16 and normalize to [0, 1] for memory efficiency scale from 8bit to 0-1
        image = image.astype(np.float16) / 255.0

        # Convert to tensor
        image = torch.from_numpy(image)

        # Normalize with mean and std (for 4 channels)
        #mean = [0.154541, 0.141640, 0.304999, 0.360158]
        #std = [0.103535, 0.129713, 0.145618, 0.172892]
        #normalize = v2.Normalize(mean=mean, std=std)
        #image = normalize(image)

        #upscale = v2.Resize((512,512)) # Added Upscale 512,512 transform
        #image = upscale(image)

        # Create sample dictionary
        sample = {
            "image": image,  # Shape: (C, H, W)
            "path": str(chip_path),
        }

        if self.transforms is not None:
            sample = self.transforms(sample)

        return sample

    def __len__(self) -> int:
        """Get the length of the dataset.

        Returns:
            Length of the dataset
        """
        return len(self.chips)

    def get_dataloader(self) -> DataLoader:
        """Get the DataLoader for this dataset.

        Returns:
            DataLoader instance
        """
        return self.dataloader




class MoCoTaskWithValidation(MoCoTask):
    """Custom MoCoTask with validation step implementation."""
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.val_losses = []
        self.train_losses = []
    
    def training_step(self, batch: Any, batch_idx: int, dataloader_idx: int = 0) -> Tensor:
        """Training step that tracks loss for epoch-level logging."""
        # Call parent training step
        loss = super().training_step(batch, batch_idx, dataloader_idx)
        
        # Store loss for epoch average
        self.train_losses.append(loss.item())
        
        return loss
    
    def validation_step(self, batch: Any, batch_idx: int, dataloader_idx: int = 0) -> None:
        """Validation step that computes loss without updating weights."""
        # Set model to eval mode for validation
        self.eval()
        
        with torch.no_grad():
            # Extract images from batch (same as training_step)
            x = batch['image']
            batch_size = x.shape[0]

            in_channels = self.hparams['in_channels']
            assert x.size(1) == in_channels or x.size(1) == 2 * in_channels

            if x.size(1) == in_channels:
                x1 = x
                x2 = x
            else:
                x1 = x[:, :in_channels]
                x2 = x[:, in_channels:]

            # Apply augmentations (same as training)
            x1 = self.augmentation1(x1)
            x2 = self.augmentation2(x2)

            m = self.hparams['moco_momentum']
            
            # Forward pass for validation (no weight updates)
            if self.hparams['version'] == 1:
                q, h1 = self.forward(x1)
                k = self.forward_momentum(x2)
                loss: Tensor = self.criterion(q, k)
                
            elif self.hparams['version'] == 2:
                q, h1 = self.forward(x1)
                k = self.forward_momentum(x2)
                loss = self.criterion(q, k)
                
            elif self.hparams['version'] == 3:
                # MoCo v3 logic (same as training but without momentum updates)
                m = cosine_schedule(self.current_epoch, self.trainer.max_epochs, m, 1)
                q1, h1 = self.forward(x1)
                q2, _ = self.forward(x2)
                k1 = self.forward_momentum(x1)
                k2 = self.forward_momentum(x2)
                loss = self.criterion(q1, k2) + self.criterion(q2, k1)
            
            # Log validation loss
            self.log('val_loss', loss, batch_size=batch_size, prog_bar=True)
            
            # Store loss for epoch average
            self.val_losses.append(loss.item())

    def on_train_epoch_end(self) -> None:
        """Called at the end of training epoch to compute average loss."""
        if self.train_losses:
            avg_train_loss = sum(self.train_losses) / len(self.train_losses)
            self.log('train_loss_epoch', avg_train_loss, prog_bar=True)
            # Get train_ssl_std from base class (used to detect collapse)
            ssl_std = getattr(self, 'avg_output_std', 0.0)
            log_msg = f"Epoch {self.current_epoch}: Training Loss = {avg_train_loss:.4f}, SSL Std = {ssl_std:.6f}"
            print(log_msg)
            
            # Also write to log file
            if self.trainer and self.trainer.logger:
                log_dir = self.trainer.logger.log_dir if hasattr(self.trainer.logger, 'log_dir') else self.trainer.logger.save_dir
                if log_dir:
                    log_file = os.path.join(log_dir, 'training_metrics.txt')
                    with open(log_file, 'a') as f:
                        f.write(log_msg + '\n')
            
            self.train_losses.clear()  # Clear for next epoch
    
    def on_validation_epoch_end(self) -> None:
        """Called at the end of validation epoch to compute average loss."""
        if self.val_losses:
            avg_val_loss = sum(self.val_losses) / len(self.val_losses)
            self.log('val_loss_epoch', avg_val_loss, prog_bar=True)
            log_msg = f"Epoch {self.current_epoch}: Validation Loss = {avg_val_loss:.4f}"
            print(log_msg)
            
            # Also write to log file
            if self.trainer and self.trainer.logger:
                log_dir = self.trainer.logger.log_dir if hasattr(self.trainer.logger, 'log_dir') else self.trainer.logger.save_dir
                if log_dir:
                    log_file = os.path.join(log_dir, 'training_metrics.txt')
                    with open(log_file, 'a') as f:
                        f.write(log_msg + '\n')
            
            self.val_losses.clear()  # Clear for next epoch

def run_training(
    train_root: str,
    val_root: str,
    output_dir: str,
    log_dir: str,
    max_epochs: int = 200,
    batch_size: int = 84,
    temperature: float = 0.07,
    resume_ckpt: str | None = None,
) -> None:
    """Run MoCo v3 Swin-Tiny SSL pretraining."""
    train_dataset = MultiSpectralChipDataset(
        root=train_root,
        split="train",
        batch_size=batch_size,
        shuffle=True,
        num_workers=8,
        pin_memory=True,
    )

    val_dataset = MultiSpectralChipDataset(
        root=val_root,
        split="val",
        batch_size=batch_size,
        shuffle=False,
        num_workers=8,
        pin_memory=True,
    )

    task = MoCoTaskWithValidation(
        model="swin_s3_tiny_224",
        weights=True,
        in_channels=4,
        layers=3,
        version=3,
        hidden_dim=4096,
        lr=1e-4,
        temperature=temperature,
        memory_bank_size=0,
        weight_decay=1e-6,
        momentum=None,
        moco_momentum=0.99,
        output_dim=256,
        schedule=None,
        augmentation1=aug1,
        augmentation2=aug2,
    )

    os.makedirs(output_dir, exist_ok=True)

    checkpoint_callback = ModelCheckpoint(
        dirpath=output_dir,
        filename="moco_v3_swin_s3_{epoch:02d}_train_{train_loss_epoch:.4f}_val_{val_loss_epoch:.4f}",
        save_top_k=-1,
        every_n_epochs=10,
        save_weights_only=False,
    )

    logger = TensorBoardLogger(save_dir=log_dir, name="swin_experiment")

    trainer = Trainer(
        max_epochs=max_epochs,
        callbacks=[checkpoint_callback],
        logger=logger,
        precision="16-mixed",
        accumulate_grad_batches=3,
        gradient_clip_val=1.0,
        log_every_n_steps=10,
    )

    trainer.fit(
        model=task,
        train_dataloaders=train_dataset.get_dataloader(),
        val_dataloaders=val_dataset.get_dataloader(),
        ckpt_path=resume_ckpt,
    )


if __name__ == "__main__":
    import argparse
    import sys

    repo_root = Path(__file__).resolve().parents[2]
    if str(repo_root) not in sys.path:
        sys.path.insert(0, str(repo_root))
    from repo_paths import ssl_output_dir, ssl_pretrain_data  # noqa: E402

    parser = argparse.ArgumentParser(description="MoCo v3 SSL pretraining (Swin Tiny, 4-channel).")
    parser.add_argument(
        "--train_data",
        default=str(ssl_pretrain_data() / "train" / "all"),
        help="Directory with unlabeled training chips.",
    )
    parser.add_argument(
        "--val_data",
        default=str(ssl_pretrain_data() / "val" / "all"),
        help="Directory with unlabeled validation chips.",
    )
    parser.add_argument(
        "--output_dir",
        default=str(ssl_output_dir() / "moco_swin_tiny"),
        help="Checkpoint output directory.",
    )
    parser.add_argument(
        "--log_dir",
        default="",
        help="TensorBoard directory (defaults to output_dir).",
    )
    parser.add_argument("--max_epochs", type=int, default=200)
    parser.add_argument("--batch_size", type=int, default=84)
    parser.add_argument(
        "--temperature",
        type=float,
        default=0.07,
        help="MoCo contrastive temperature (default: 0.07, matches epoch-79 Swin run).",
    )
    parser.add_argument("--resume_ckpt", default=None, help="Optional checkpoint to resume from.")
    cli = parser.parse_args()

    log_dir = cli.log_dir or cli.output_dir
    run_training(
        train_root=cli.train_data,
        val_root=cli.val_data,
        output_dir=cli.output_dir,
        log_dir=log_dir,
        max_epochs=cli.max_epochs,
        batch_size=cli.batch_size,
        temperature=cli.temperature,
        resume_ckpt=cli.resume_ckpt,
    )
